name: NodeJS with Webpack

on:
  push:
    branches: [ "master", "ci-cd" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: npm install
      - name: Build tracker
        run: npm run tracker:build:prod
      - name: Build admin
        run: npm run admin:build:prod
      - name: Archive Production Artifact Admin
        uses: actions/upload-artifact@master
        with:
          name: admin-dist
          path: packages/admin/build
      - name: Archive Production Artifact Tracker
        uses: actions/upload-artifact@master
        with:
          name: tracker-dist
          path: packages/tracker/build
