name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Build
      run: |
        npm install
        npm run tracker:build:prod
        npm run admin:build:prod

    - name: Deploy
      run: |
        npm install
        npm run tracker:deploy:prod
        npm run admin:deploy:prod
