export const bbtRegions = [
  { value: "moscow", label: "Москва" },
  { value: "saint-petersburg", label: "Санкт-Петербург" },
  { value: "central", label: "Центральный" },
  { value: "kaliningrad", label: "Калининград" },
  { value: "south-west", label: "Южный (Западная часть)" },
  { value: "south-east", label: "Южный (Восточная часть)" },
  { value: "caucasus", label: "Кавказ" },
  { value: "volga", label: "Поволжье" },
  { value: "golden-ring", label: "Золотое Кольцо" },
  { value: "tatarstan", label: "Татарстан" },
  { value: "bashkortostan", label: "Башкирия" },
  { value: "north-west", label: "Северо-запад" },
  { value: "ural", label: "Урал" },
  { value: "western-siberia", label: "Западная Сибирь" },
  { value: "eastern-siberia", label: "Восточная Сибирь" },
  { value: "far-east", label: "Дальний Восток" },
  { value: "primorsky-krai", label: "Приморский Край" },
];
